namespaceOverride: argo
server:
  extraArgs:
  - --auth-mode=server

controller:
  # Default values that will apply to all Workflows from this controller, unless overridden on the Workflow-level
  workflowDefaults:
    metadata:
      annotations:
        argo: workflows
    spec:
      ttlStrategy:
        # Keep the workflow pods & logs available for 30 days
        secondsAfterCompletion: 2592000
        secondsAfterSuccess: 2592000
        secondsAfterFailure: 2592000

useDefaultArtifactRepo: true
artifactRepository:
  archiveLogs: true
  gcs:
    bucket: rhacs-infra-artifacts
    serviceAccountKeySecret:
      name: gcs-credentials
      key: credentials.json
