---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-simulate
  namespace: default
spec:
  templates:
    - name: simulate
      inputs:
        parameters:
        - name: delay-seconds
        - name: outcome
        - name: test-gcs
      script:
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
        command: [bash]
        source: |
          set -x

          delay() {
            start=0
            while sleep 1; do
              if [[ $((start++)) -ge {{ "{{" }}inputs.parameters.delay-seconds{{ "}}" }} ]]; then
                break
              fi
            done
          }

          upload_or_delete_gcs_object() {
            gcloud auth activate-service-account --key-file /tmp/google-credentials.json
            gcloud config set core/disable_prompts True

            BUCKET_NAME="infra-e2e-upload-test"
            FILE="{{ "{{" }}workflow.name{{ "}}" }}"
            touch "${FILE}"

            DESTINATION="gs://${BUCKET_NAME}/${FILE}"

            if gsutil -q stat "${DESTINATION}"; then
              echo "File exists. Deleting..."
              gsutil rm "${DESTINATION}"
            else
              echo "File does not exist. Proceeding to upload."
              gsutil cp "${FILE}" "${DESTINATION}"
            fi
          }

          if [[ "{{ "{{" }}inputs.parameters.test-gcs{{ "}}" }}" == "true" ]]; then
            upload_or_delete_gcs_object
          fi

          if [[ {{ "{{" }}inputs.parameters.delay-seconds{{ "}}" }} -gt 0 ]]; then
            delay
          fi

          [[ "{{ "{{" }}inputs.parameters.outcome{{ "}}" }}" == "success" ]] || exit 1

        volumeMounts:
          - name: credentials
            mountPath: /tmp
