##########
#  demo  #
##########
- id: demo
  name: StackRox Demo
  description: Demo running StackRox 3.65.0
  availability: default
  workflow: configuration/workflow-demo.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: main-image
      value: stackrox.io/main:3.65.0
      kind: hardcoded

    - name: k8s-version
      value: default
      kind: hardcoded

  artifacts:
    - name: kubeconfig
      description: Kube config for connecting to cluster

    - name: SSH_ACCESS
      description: Instructions for obtaining SSH access to instances in your cluster

    - name: tfstate
      description: Terraform state file

    - name: url
      description: URL of StackRox UI
      tags: [url]

    - name: roxctl
      tags: [internal]

#############
#  qa-demo  #
#############
- id: qa-demo
  name: StackRox Demo for QA testing
  description: TESTING ONLY - Demo running a provided StackRox version
  availability: alpha
  workflow: configuration/workflow-qa-demo.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: main-image
      description: StackRox Central image Docker name
      value: stackrox.io/main:3.65.0
      help: This must be a fully qualified image e.g. docker.io/stackrox/main:3.65.0

    - name: scanner-image
      description: StackRox Scanner image Docker name
      kind: optional
      help: If unspecified, this will be derived from the central image

    - name: scanner-db-image
      description: StackRox Scanner DB image Docker name
      kind: optional
      help: If unspecified, this will be derived from the central image

    - name: k8s-version
      description: kubernetes version
      value: default
      kind: optional

  artifacts:
    - name: kubeconfig
      description: Kube config for connecting to cluster

    - name: SSH_ACCESS
      description: Instructions for obtaining SSH access to instances in your cluster

    - name: tfstate
      description: Terraform state file

    - name: url
      description: URL of StackRox UI
      tags: [url]

    - name: roxctl
      tags: [internal]

#################
#  gke-default  #
#################
- id: gke-default
  name: GKE Default
  description: GKE cluster running the default version
  availability: stable
  workflow: configuration/workflow-gke-default.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: nodes
      description: number of nodes
      value: "3"
      kind: optional

    - name: machine-type
      description: node machine type
      value: e2-standard-4
      kind: optional

    - name: k8s-version
      description: GKE kubernetes version
      value: ""
      kind: optional
      help: |
        e.g. 1.19.12-gke.2100. Use 'gcloud container get-server-config --zone=us-central1' to see all versions.

    - name: pod-security-policy
      description: Enables the pod security policy admission controller for the cluster
      value: false
      kind: optional

    - name: gcp-image-type
      description: The GCP image type to use for the cluster
      value: ubuntu
      kind: optional

    - name: gcp-zone
      description: The zone in GCP to delete the cluster from
      value: us-central1-a
      kind: optional

  artifacts:
    - name: kubeconfig
      description: Kube config for connecting to this cluster

    - name: connect
      description: Shell script for adding this clusters connect information to your kubeconfig
      tags: [connect]

    - name: SSH_ACCESS
      description: Instructions for obtaining SSH access to instances in your cluster

#####################
#  openshift-multi  #
#####################
- id: openshift-multi
  name: OpenShift 3.11
  description: OpenShift 3.11 cluster
  availability: alpha
  workflow: configuration/workflow-openshift-multi.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: crio
      description: should CRI-O be used as the container runtime
      value: true
      kind: optional

    - name: nodes
      description: number of worker nodes
      value: "2"
      kind: optional

    - name: machine-type
      description: node machine type
      value: e2-standard-4
      kind: optional

    - name: zone
      description: Google Cloud zone to deploy infrastructure into.
      value: us-east1-d
      kind: optional

    - name: install-monitoring
      description: Install the OpenShift monitoring stack
      help: This is a prometheus/grafana/alertmanager stack. See the logs/artifacts for access info.
      value: true
      kind: optional

    - name: install-metrics
      description: Install metrics
      help: For example to get the output of `oc adm top pods`
      value: false
      kind: optional

  artifacts:
    - name: kubeconfig
      description: Kube config for connecting to this cluster

    - name: console_url
      description: The URL for the openshift console
      tags: [url]

    - name: console_password
      description: The password for the console admin account

    - name: grafana_url
      description: The URL for the grafana instance (if monitoring is enabled)

    - name: prometheus_url
      description: The URL for the prometheus instance (if monitoring is enabled)

    - name: SSH_ACCESS
      description: Instructions for obtaining SSH access to instances in your cluster

    - name: data
      description: An archive with various bits

####################
#  openshift-4     #
####################
- id: openshift-4
  name: OpenShift 4.x
  description: OpenShift 4.x OCP or OKD cluster
  availability: alpha
  workflow: configuration/workflow-openshift-4.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: openshift-version
      description: openshift release from OCP or OKD
      value: ocp/stable-4.7
      kind: optional
      help: |
        The latest RedHat enterprise OCP releases can be found at https://mirror.openshift.com/pub/openshift-v4/clients/ocp/.
        For OCP use the path to one of the stable releases e.g. ocp/stable-4.
        Opensource OKD releases are at https://github.com/openshift/okd/releases.
        For OKD use the release tag e.g. 4.7.0-0.okd-2021-02-25-144700.

    - name: pull-secret
      description: A cloud.redhat.com pull secret
      kind: optional
      fromFile: true
      help: |
        Use this if you want to associate this cluster with a particular cloud.redhat.com account.
        Get the pull secret from: https://cloud.redhat.com/openshift/install/pull-secret
        You might do this for access to OpenShift Cluster Manager for example.
        By default an infra automation account is used.

    - name: master-node-type
      description: the type of master nodes
      value: n1-standard-4
      kind: optional

    - name: master-node-count
      description: number of master nodes
      value: 3
      kind: optional

    - name: worker-node-type
      description: the type of worker nodes
      value: n1-standard-4
      kind: optional

    - name: worker-node-count
      description: number of worker nodes
      value: 3
      kind: optional

    - name: region
      description: Google Cloud zone to deploy infrastructure into.
      value: us-east1
      kind: optional

  artifacts:
    - name: kubeconfig
      description: Kube config for connecting to this cluster

    - name: kubeadmin-password
      description: The kubeadmin user password for the openshift console

    - name: url
      description: The URL for the openshift console
      tags: [url]

    - name: SSH_ACCESS
      description: Instructions for obtaining SSH access to instances in your cluster

######################
#  openshift-4-demo  #
######################
- id: openshift-4-demo
  name: OpenShift 4.x Demo
  description: OpenShift 4.x Demo
  availability: alpha
  workflow: configuration/workflow-openshift-4-demo.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: ansible-demo-tag
      description: Ansible-demo image tag
      value: latest
      kind: optional
      help: |
        The image tag to use for the ansible-demo provisioner. This should generally be 'latest' but is parameterized to support testing and emergency use-cases. See https://github.com/stackrox/ansible-demo for details.

  artifacts:
    - name: admin-password
      description: Admin password for StackRox console

    - name: kubeconfig
      description: Kube config for connecting to this cluster

    - name: SSH_ACCESS
      description: Instructions for obtaining SSH access to instances in your cluster

    - name: url-openshift
      description: The URL for the OpenShift console

    - name: url-stackrox
      description: The URL for the StackRox console
      tags: [url]

    - name: data
      description: An archive that includes ssh keys to connect to cluster nodes

#####################
#  AWS EKS          #
#####################
- id: eks
  name: EKS
  description: AWS EKS cluster
  availability: alpha
  workflow: configuration/workflow-eks.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: user-arns
      description: AWS user ARNs that will get access to the cluster
      value: arn:aws:iam::393282794030:user/joey@stackrox.com

    - name: nodes
      description: number of nodes
      value: "2"
      kind: optional

    - name: machine-type
      description: node machine type
      value: m5.xlarge
      kind: optional

    - name: k8s-version
      description: kubernetes version
      kind: optional
      help: Use this to override the default version used by EKS

    - name: region
      description: AWS region
      value: us-west-2
      kind: optional

#####################
#  AWS KOPS         #
#####################
- id: kops
  name: KOPS on AWS
  description: A cluster created with KOPS on AWS
  availability: alpha
  workflow: configuration/workflow-kops.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: kops-version
      description: KOPS version
      value: 1.18.1
      kind: optional

    - name: k8s-version
      description: kubernetes version (must be <= KOPS version)
      value: 1.18.1
      kind: optional

    - name: master-count
      description: number of master nodes (must be odd number)
      value: "1"
      kind: optional

    - name: master-instance-type
      description: EC2 instance type for k8s masters
      value: c5.large
      kind: optional

    - name: node-count
      description: number of nodes in the cluster
      value: "3"
      kind: optional

    - name: node-instance-type
      description: EC2 instance type for k8s nodes
      value: c5.xlarge
      kind: optional

    - name: cni
      description: K8s network plugin to use
      value: calico
      kind: optional

    - name: region
      description: AWS region
      value: us-east-1
      kind: optional

#####################
#  Azure AKS        #
#####################
- id: aks
  name: AKS
  description: Azure AKS cluster
  availability: alpha
  workflow: configuration/workflow-aks.yaml
  parameters:
    - name: name
      description: cluster name
      value: example1

    - name: nodes
      description: number of nodes
      value: "3"
      kind: optional

    - name: machine-type
      description: node machine type
      value: standard_d4s_v3
      kind: optional

    - name: k8s-version
      description: kubernetes version
      kind: optional
      help: Use this to override the default version used by AKS

    - name: network-plugin
      description: The Kubernetes network plugin to use.
      kind: optional
      help: 'Allowed values: azure, kubenet. Specify "azure" for advanced networking configurations. Defaults to "kubenet".'

    - name: network-policy
      description: The Kubernetes network policy to use.
      kind: optional
      help: |
        Using together with "azure" network plugin.
        Specify "azure" for Azure network policy manager and "calico" for calico network policy controller.
        Defaults to "" (network policy disabled).

  artifacts:
    - name: kubeconfig
      description: Kube config for connecting to this cluster

    - name: connect
      description: Shell script for adding this clusters connect information to your kubeconfig
      tags: [connect]

    - name: data
      description: An archive that includes ssh keys to connect to cluster nodes
