apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: janitor-delete-openshift-4-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
  volumes:
    - name: credentials
      secret:
        secretName: openshift-4-gcp-service-account

  templates:
    - name: start
      steps:
        - - name: destroy
            template: destroy


    - name: destroy
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-openshift-4-{{ .Chart.Annotations.automationFlavorsVersion }}
        imagePullPolicy: Always
        command:
          - entrypoint.sh
        args:
          - destroy
          - '{{ "{{" }}workflow.parameters.name{{ "}}" }}'
        env:
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: openshift-4-gcp-service-account
                key: google-credentials.json
          - name: GCP_PROJECT
            value : "acs-team-temp-dev"
        volumeMounts:
          - name: data
            mountPath: /data
