apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: janitor-delete-openshift-rosa-
spec:
  entrypoint: delete
  arguments:
    parameters:
      - name: name
      - name: aws-region
        value: "us-east-1"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi

  templates:
    - name: delete
      steps:
        - - name: destroy
            template: destroy

    - name: destroy
      activeDeadlineSeconds: 3600
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-rosa-{{ .Chart.Annotations.automationFlavorsVersion }}
        imagePullPolicy: Always
        command:
          - ./entrypoint.sh
        args:
          - destroy
          - '{{ "{{" }}workflow.parameters.name{{ "}}" }}'
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: OPENSHIFT_CLUSTER_MANAGER_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: OPENSHIFT_CLUSTER_MANAGER_API_TOKEN
          - name: REDHAT_PULL_SECRET_BASE64
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: REDHAT_PULL_SECRET_BASE64
          - name: AWS_REGION
            value: '{{ "{{" }}workflow.parameters.aws-region{{ "}}" }}'
        volumeMounts:
          - name: data
            mountPath: /data
