issuer: "https://auth.stage.redhat.com/auth/realms/EmployeeIDP"
clientID: "rhacs-dev-infra"
clientSecret: "clientSecret-example"
sessionSecret: "sessionSecret-example"
endpoint: {{ if eq .Values.deployment "local" }}localhost:8443{{ else }}dev.infra.rox.systems{{ end }}
claims:
  - key: 'realm_access.roles'
    op: 'in'
    value: 'rover-group-example'
