apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-url-artifact-
spec:
  entrypoint: start
  onExit: stop
  arguments:
    parameters:
      - name: name
        description: cluster name

  templates:
    - name: start
      steps:
        - - name: create
            template: create
        - - name: wait
            template: wait
    - name: stop
      steps:
        - - name: destroy
            template: destroy

    - name: create
      outputs:
        artifacts:
          - name: url
            path: /tmp/url
            optional: true
      script:
        image: debian:9.4
        command: [bash]
        source: |
          set -x
          start=0
          while sleep 1; do
            if [[ $((start++)) -ge 10 ]]; then
              break
            fi
          done
          echo {{ "{{" }} workflow.name {{ "}}" }} {{ "{{" }} workflow.uid {{ "}}" }} > /tmp/url

    - name: wait
      suspend: {}

    - name: destroy
      script:
        image: debian:9.4
        command: [bash]
        source: |
          set -x
          start=0
          while sleep 1; do
            if [[ $((start++)) -ge 10 ]]; then
              break
            fi
          done
