apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: simulate-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: create-delay-seconds
      - name: create-outcome
      - name: destroy-delay-seconds
      - name: destroy-outcome

  templates:
    - name: start
      steps:
        - - name: create
            templateRef:
              name: test-simulate
              template: simulate
            arguments:
              parameters:
              - name: delay-seconds
                value: '{{ "{{" }}workflow.parameters.create-delay-seconds{{ "}}" }}'
              - name: outcome
                value: '{{ "{{" }}workflow.parameters.create-outcome{{ "}}" }}'

        - - name: wait
            templateRef:
              name: common
              template: wait

        - - name: destroy
            templateRef:
              name: test-simulate
              template: simulate
            arguments:
              parameters:
              - name: delay-seconds
                value: '{{ "{{" }}workflow.parameters.destroy-delay-seconds{{ "}}" }}'
              - name: outcome
                value: '{{ "{{" }}workflow.parameters.destroy-outcome{{ "}}" }}'
