apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gke-default-
  labels:
    needsExit: true
  annotations:
    infra.stackrox.com/lifespan: 0s
    infra.stackrox.com/lifespanlast: 1s
spec:
  entrypoint: start
  onExit: stop
  arguments:
    parameters:
      - name: name
      - name: nodes
      - name: machine-type
      - name: k8s-version
        value: ""
      - name: pod-security-policy
        value: ""
      - name: gcp-image-type
        value: ""
      - name: gcp-zone
        value: ""

  volumes:
    - name: credentials
      secret:
        secretName: google-credentials

  templates:
    - name: start
      steps:
        - - name: create
            template: echo
            arguments:
              parameters:
              - name: message
                value: "create"
          - name: wait
            template: wait
            arguments:
              parameters:
              - name: oldlifespan
                value: "0h0m0s"

    - name: stop
      steps:
        - - name: destroy
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.name}}"

    - name: wait
      inputs:
        parameters:
          - name: oldlifespan
      steps:
        - - name: echo1
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{inputs.parameters.oldlifespan}} =? {{workflow.annotations.infra.stackrox.com/lifespan}}"
        - - name: echoDS
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{= sprig.toDate('2006-01-02T15:04:05Z07:00', workflow.creationTimestamp.RFC3339) }}"
        - - name: echoDlife
            template: echo
            arguments:
              parameters:
              - name: message
                value: "expiration={{= sprig.dateModify(inputs.parameters.lifespan, sprig.toDate('2006-01-02T15:04:05Z07:00', workflow.creationTimestamp.RFC3339)) }}"
        - - name: echo2
            template: echo
            when: "'{{inputs.parameters.oldlifespan}}' =~ '{{workflow.annotations.infra.stackrox.com/lifespan}}'"
            arguments:
              parameters:
              - name: message
                value: "{{inputs.parameters.oldlifespan}} =~ {{workflow.annotations.infra.stackrox.com/lifespan}}"
        - - name: echo4
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{inputs.parameters.oldlifespan}}, {{workflow.annotations.infra.stackrox.com/lifespan}}"
        - - name: delay
            template: delay
        - - name: shortloop
            template: wait
            when: "'{{inputs.parameters.oldlifespan}}' =~ '{{workflow.annotations.infra.stackrox.com/lifespan}}'"
            arguments:
              parameters:
                - name: oldlifespan
                  value: "{{workflow.annotations.infra.stackrox.com/lifespan}}"  # preserve value; prevent pass by reference
        - - name: timeupdate
            template: timeupdate
            arguments:
              parameters:
                - name: lifespan
                  value: "{{workflow.annotations.infra.stackrox.com/lifespan}}"  # preserve value; prevent pass by reference
        - - name: loop
            template: wait
            arguments:
              parameters:
                - name: oldlifespan
                  value: "{{workflow.annotations.infra.stackrox.com/lifespan}}"  # preserve value; prevent pass by reference

    - name: echo
      inputs:
        parameters:
        - name: message
      container:
        image: alpine:3.7
        command: [echo, "{{inputs.parameters.message}}"]

    - name: delay
      suspend:
        duration: "4"

    - name: timeupdate
      inputs:
        parameters:
          - name: lifespan
      steps:
        - - name: echo1
            template: echo
            arguments:
              parameters:
              - name: message
                value: "expiration={{= sprig.dateModify(inputs.parameters.lifespan, sprig.toDate('2006-01-02T15:04:05Z07:00', workflow.creationTimestamp.RFC3339)) }}"
        - - name: setlabels
            template: label
            arguments:
              parameters:
              - name: labels
                value: "expiration={{= sprig.dateModify(inputs.parameters.lifespan, sprig.toDate('2006-01-02T15:04:05Z07:00', workflow.creationTimestamp.RFC3339)) }}"

    - name: label
      inputs:
        parameters:
        - name: labels
      script:
        image: quay.io/stackrox-io/ci:automation-flavors-gke-default-0.7.6-3-g1ce65fe441-snapshot
        imagePullPolicy: Always
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /tmp/google-credentials.json
        command: [bash, -x]
        source: |
          labels="{{inputs.parameters.labels}}"
          gcloud auth activate-service-account --key-file /tmp/google-credentials.json;
          gcloud auth list;
          gcloud config set compute/zone "{{workflow.parameters.gcp-zone}}";
          gcloud config set core/disable_prompts True;
          gcloud container clusters update \
            "{{workflow.parameters.name}}"\
            --project=srox-temp-dev-test\
            "--update-labels=${labels}";
          echo "$labels" | tee /outputs/value.txt
        volumeMounts:
          - name: credentials
            mountPath: /tmp
      outputs:
        parameters:
        - name: value
          valueFrom:
            path: /outputs/value.txt
               
    - name: create
      activeDeadlineSeconds: 3600
      outputs:
        artifacts:
          - name: kubeconfig
            path: /outputs/kubeconfig
            mode: 0644
            archive:
              none: {}
          - name: connect
            path: /outputs/connect.sh
            mode: 0755
            archive:
              none: {}
          - name: SSH_ACCESS
            path: /outputs/SSH_ACCESS.md
            archive:
              none: {}
        parameters:
          - name: cluster_name
            valueFrom:
              path: /outputs/cluster_name
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-gke-default-0.7.6-3-g1ce65fe441-snapshot
        imagePullPolicy: Always
        command:
          - /usr/bin/entrypoint
        args:
          - create
          - "--name={{workflow.parameters.name}}"
          - "--nodes={{workflow.parameters.nodes}}"
          - "--machine-type={{workflow.parameters.machine-type}}"
          - --gcp-project=srox-temp-dev-test
          - --creation-source=infra
          - --labels=lifespan={{workflow.annotations.infra.stackrox.com/lifespan}}
          - --k8s-version={{workflow.parameters.k8s-version}}
          - --pod-security-policy={{workflow.parameters.pod-security-policy}}
          - --gcp-image-type={{workflow.parameters.gcp-image-type}}
          - --gcp-zone={{workflow.parameters.gcp-zone}}
        volumeMounts:
          - name: credentials
            mountPath: /tmp

    - name: destroy
      activeDeadlineSeconds: 3600
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-gke-default-0.5.3
        imagePullPolicy: Always
        command:
          - /usr/bin/entrypoint
        args:
          - destroy
          - "--name={{workflow.parameters.name}}"
          - --gcp-project=srox-temp-dev-test
          - --gcp-zone={{workflow.parameters.gcp-zone}}
        volumeMounts:
          - name: credentials
            mountPath: /tmp
