apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: example-

spec:
  entrypoint: start
  onExit: stop

  arguments:
    parameters:
      - name: create-sleep
      - name: create-success
      - name: destroy-sleep
      - name: destroy-success

  templates:
    - name: start
      steps:
        - - name: create
            template: create
            arguments:
              parameters:
                - name: sleep
                  value: "{{workflow.parameters.create-sleep}}"
                - name: success
                  value: "{{workflow.parameters.create-success}}"

        - - name: wait
            template: wait

    - name: stop
      steps:
        - - name: destroy
            template: destroy
            arguments:
              parameters:
                - name: sleep
                  value: "{{workflow.parameters.destroy-sleep}}"
                - name: success
                  value: "{{workflow.parameters.destroy-success}}"

    - name: create
      inputs:
        parameters:
          - name: sleep
          - name: success

      container:
        image: gcr.io/stackrox-infra/automation-flavors/example:v0.0.0-13-g1eb47b1
        args:
          - create
          - "--sleep={{inputs.parameters.sleep}}"
          - "--success={{inputs.parameters.success}}"

    - name: wait
      suspend: {}

    - name: destroy
      inputs:
        parameters:
          - name: sleep
          - name: success

      container:
        image: gcr.io/stackrox-infra/automation-flavors/example:v0.0.0-13-g1eb47b1
        args:
          - destroy
          - "--sleep={{inputs.parameters.sleep}}"
          - "--success={{inputs.parameters.success}}"
