apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kops-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: kops-version
        value: ""
      - name: k8s-version
        value: ""
      - name: master-count
        value: ""
      - name: master-instance-type
        value: ""
      - name: node-count
        value: ""
      - name: node-instance-type
        value: ""
      - name: cni
        value: ""
      - name: region
        value: ""
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Mi

  templates:
    - name: start
      steps:
        - - name: create
            template: create

        - - name: wait
            template: wait

        - - name: destroy
            template: destroy

    - name: create
      activeDeadlineSeconds: 3600
      outputs:
        artifacts:
          - name: kubeconfig
            path: /data/kube.yaml
            archive:
              none: {}
          - name: data
            path: /data
            archive:
              tar: {}
      container:
        image: gcr.io/stackrox-infra/automation-flavors/kops:0.2.13-27-g6ae68cace5-snapshot
        imagePullPolicy: Always
        args:
          - create
          - "{{workflow.parameters.name}}"
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-access-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-access-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: DESIRED_KOPS_VERSION
            value: "{{workflow.parameters.kops-version}}"
          - name: TF_VAR_k8s_version
            value: "{{workflow.parameters.k8s-version}}"
          - name: TF_VAR_master_count
            value: "{{workflow.parameters.master-count}}"
          - name: TF_VAR_master_instance_type
            value: "{{workflow.parameters.master-instance-type}}"
          - name: TF_VAR_node_count
            value: "{{workflow.parameters.node-count}}"
          - name: TF_VAR_node_instance_type
            value: "{{workflow.parameters.node-instance-type}}"
          - name: TF_VAR_cni
            value: "{{workflow.parameters.cni}}"
          - name: TF_VAR_region
            value: "{{workflow.parameters.region}}"
          - name: TF_VAR_creation_source
            value: "infra"
        volumeMounts:
          - name: data
            mountPath: /data

    - name: wait
      suspend: {}

    - name: destroy
      activeDeadlineSeconds: 3600
      container:
        image: gcr.io/stackrox-infra/automation-flavors/kops:0.2.13-27-g6ae68cace5-snapshot
        imagePullPolicy: Always
        args:
          - destroy
          - "{{workflow.parameters.name}}"
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-access-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-access-secrets
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: data
            mountPath: /data
