apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: openshift-4-demo-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: openshift-version
        value: ""
      - name: image-registry
      - name: main-image-tag
      - name: scanner-image-tag
      - name: scanner-db-image-tag
      - name: collector-slim-image-tag
      - name: central-services-helm-chart-version
      - name: secured-cluster-services-helm-chart-version
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
  volumes:
    - name: credentials
      secret:
        secretName: google-credentials-openshift-4
    - name: demo-secrets
      secret:
        secretName: demo-secrets

  templates:
    - name: start
      steps:
        - - name: validate
            template: validate

        - - name: create
            template: create

        - - name: pre-install
            template: pre-install

        - - name: run-ansible-demo
            template: run-ansible-demo
            continueOn:
              failed: true
            arguments:
              parameters:
              - name: admin-password
                value: "{{steps.pre-install.outputs.parameters.admin-password}}"
              - name: kubeconfig-base64
                value: "{{steps.pre-install.outputs.parameters.kubeconfig-base64}}"

        - - name: gather
            template: gather

        - - name: wait
            template: wait

        - - name: destroy
            template: destroy

    - name: validate
      script:
        image: ubuntu:20.04
        command: [ bash ]
        source: |
          main_image_tag="{{ workflow.parameters.main-image-tag }}"
          if [[ -n "$main_image_tag" && ! "$main_image_tag" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?$ ]]; then
            echo >&2 "Only released version are currently support"
            exit 1
          fi

    - name: create
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-openshift-4-0.6.10
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            mountPath: /data
        command:
          - entrypoint.sh
        args:
          - create
          - "{{workflow.parameters.name}}"
          - srox-temp-dev-test
          - openshift.infra.rox.systems
        env:
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: google-credentials-openshift-4
                key: google-credentials.json
          - name: PULL_SECRET
            valueFrom:
              secretKeyRef:
                name: redhat-pull-secret
                key: REDHAT_PULL_SECRET
          - name: OPENSHIFT_VERSION
            value: "{{workflow.parameters.openshift-version}}"
          - name: MASTER_NODE_COUNT
            value: "3"
          - name: WORKER_NODE_COUNT
            value: "3"
          - name: MASTER_NODE_TYPE
            value: "n1-standard-4"
          - name: WORKER_NODE_TYPE
            value: "n1-standard-4"
          - name: REGION
            value: "us-east1"

    - name: pre-install
      script:
        image: rnix/openssl-gost
        volumeMounts:
          - name: data
            mountPath: /data
        command: [sh]
        source: |
          openssl rand -base64 32 | tr "+/" "_#"  | cut -c 1-20 > /data/admin_password
          base64 /data/auth/kubeconfig | tr -d "\n" > /data/auth/kubeconfig_base64
          subdomain="apps.{{workflow.parameters.name}}.openshift.infra.rox.systems"
          echo "https://console-openshift-console.${subdomain}" > /data/url-openshift
          echo "https://central-stackrox.${subdomain}" > /data/url-stackrox
      outputs:
        parameters:
          - name: admin-password
            valueFrom:
              path: /data/admin_password
          - name: kubeconfig-base64
            valueFrom:
              path: /data/auth/kubeconfig_base64

    - name: run-ansible-demo
      inputs:
        parameters:
          - name: admin-password
          - name: kubeconfig-base64
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-openshift-4-demo-0.6.10-1-gf2aa0d495f-snapshot
        imagePullPolicy: Always
        command:
          - ansible-playbook
        args: ["-i", "inventory.yml", "main.yml"]
        env:
          - name: IMAGE_PULL_USER
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: QUAY_RHACS_ENG_RO_USERNAME
          - name: IMAGE_PULL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: QUAY_RHACS_ENG_RO_PASSWORD
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: google-credentials-openshift-4
                key: google-credentials.json
          - name: CENTRAL_PORT
            value: "443"
          - name: ORCHESTRATOR
            value: openshift
          - name: ADMIN_PASSWORD
            value: "{{ inputs.parameters.admin-password }}"
          - name: KUBECONFIG_BASE64
            value: "{{ inputs.parameters.kubeconfig-base64 }}"
          - name: IMAGE_REGISTRY
            value: "{{ workflow.parameters.image-registry }}"
          - name: MAIN_IMAGE_TAG
            value: "{{ workflow.parameters.main-image-tag }}"
          - name: SCANNER_IMAGE_TAG
            value: "{{ workflow.parameters.scanner-image-tag }}"
          - name: SCANNER_DB_IMAGE_TAG
            value: "{{ workflow.parameters.scanner-db-image-tag }}"
          - name: COLLECTOR_SLIM_IMAGE_TAG
            value: "{{ workflow.parameters.collector-slim-image-tag }}"
          - name: CENTRAL_SERVICES_HELM_CHART_VERSION
            value: "{{ workflow.parameters.central-services-helm-chart-version }}"
          - name: SECURED_CLUSTER_SERVICES_HELM_CHART_VERSION
            value: "{{ workflow.parameters.secured-cluster-services-helm-chart-version }}"
          - name: ANSIBLE_STDOUT_CALLBACK
            value: debug
          - name: AUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: AUTH_CLIENT_ID
          - name: AUTH_DOMAIN
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: AUTH_DOMAIN
        volumeMounts:
          - name: data
            mountPath: /data

    - name: gather
      container:
        image: busybox
        imagePullPolicy: Always
        command: [echo, "gathering artifacts"]
        volumeMounts:
          - name: data
            mountPath: /data
      outputs:
        artifacts:
          - name: admin-password
            path: /data/admin_password
            archive:
              none: {}
          - name: kubeconfig
            path: /data/auth/kubeconfig
            archive:
              none: {}
          - name: SSH_ACCESS
            path: /data/SSH_ACCESS.md
            archive:
              none: {}
          - name: url-openshift
            path: /data/url-openshift
            archive:
              none: {}
          - name: url-stackrox
            path: /data/url-stackrox
            archive:
              none: {}
          - name: dotenv
            path: /data/dotenv
            archive:
              none: {}
          - name: data
            path: /data
            archive:
              tar: {}

    - name: wait
      suspend: {}

    - name: destroy
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-openshift-4-0.6.10
        imagePullPolicy: Always
        command:
          - entrypoint.sh
        args:
          - destroy
        env:
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: google-credentials-openshift-4
                key: google-credentials.json
        volumeMounts:
          - name: data
            mountPath: /data
