apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: openshift-4-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: openshift-version
      - name: master-node-type
      - name: master-node-count
      - name: worker-node-type
      - name: worker-node-count
      - name: region
      - name: pull-secret
      - name: fips-enabled
      - name: trusted-certs-enabled
      - name: credentials-mode
      - name: keep-failed-cluster
      - name: ssd-storage-class
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi
  volumes:
    - name: credentials
      secret:
        secretName: openshift-4-gcp-service-account

  templates:
    - name: start
      steps:
        - - name: create
            templateRef:
              name: create
              template: openshift-4
            arguments:
              parameters:
              - name: name
                value: '{{ "{{" }}workflow.parameters.name{{ "}}" }}'
              - name: pull-secret
                value: '{{ "{{" }}workflow.parameters.pull-secret{{ "}}" }}'
              - name: openshift-version
                value: '{{ "{{" }}workflow.parameters.openshift-version{{ "}}" }}'
              - name: master-node-count
                value: '{{ "{{" }}workflow.parameters.master-node-count{{ "}}" }}'
              - name: worker-node-count
                value: '{{ "{{" }}workflow.parameters.worker-node-count{{ "}}" }}'
              - name: master-node-type
                value: '{{ "{{" }}workflow.parameters.master-node-type{{ "}}" }}'
              - name: worker-node-type
                value: '{{ "{{" }}workflow.parameters.worker-node-type{{ "}}" }}'
              - name: region
                value: '{{ "{{" }}workflow.parameters.region{{ "}}" }}'
              - name: fips-enabled
                value: '{{ "{{" }}workflow.parameters.fips-enabled{{ "}}" }}'
              - name: trusted-certs-enabled
                value: '{{ "{{" }}workflow.parameters.trusted-certs-enabled{{ "}}" }}'
              - name: credentials-mode
                value: '{{ "{{" }}workflow.parameters.credentials-mode{{ "}}" }}'
              - name: keep-failed-cluster
                value: '{{ "{{" }}workflow.parameters.keep-failed-cluster{{ "}}" }}'
              - name: ssd-storage-class
                value: '{{ "{{" }}workflow.parameters.ssd-storage-class{{ "}}" }}'


        - - name: gather
            templateRef:
              name: gather
              template: openshift-4

        - - name: wait
            templateRef:
              name: wait
              template: openshift-4

        - - name: destroy
            templateRef:
              name: destroy
              template: openshift-4
            arguments:
              parameters:
              - name: name
                value: '{{ "{{" }}workflow.parameters.name{{ "}}" }}'
