apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-

spec:
  entrypoint: start
  onExit: stop
  imagePullSecrets:
    - name: docker-io-pull-secret
    - name: stackrox-io-pull-secret

  arguments:
    parameters:
      - name: name
      - name: main-image
      - name: k8s-version

  volumes:
    - name: credentials
      secret:
        secretName: google-credentials-demo

  templates:
    - name: start
      steps:
        - - name: roxctl
            template: roxctl

        - - name: create
            template: create
            arguments:
              artifacts:
                - name: roxctl
                  from: "{{steps.roxctl.outputs.artifacts.roxctl}}"

        - - name: wait
            template: wait

    - name: stop
      steps:
        - - name: destroy
            template: destroy
            arguments:
              artifacts:
                - name: tfstate
                  from: "{{workflow.outputs.artifacts.global-tfstate}}"
                - name: tfvars
                  from: "{{workflow.outputs.artifacts.global-tfvars}}"

    - name: roxctl
      activeDeadlineSeconds: 120
      outputs:
        artifacts:
          - name: roxctl
            path: /assets/downloads/cli/roxctl-linux
      container:
        image: "{{workflow.parameters.main-image}}"
        imagePullPolicy: Always
        args:
          - version
          - "--json"

    - name: create
      activeDeadlineSeconds: 3600
      inputs:
        artifacts:
          - name: roxctl
            path: /usr/bin/roxctl

      outputs:
        artifacts:
          - name: kubeconfig
            path: /data/kubeconfig.yaml
            optional: true

          - name: tfstate
            globalName: global-tfstate
            path: /data/terraform.tfstate
            optional: true

          - name: tfvars
            globalName: global-tfvars
            path: /data/tfvars
            optional: true

          - name: url
            path: /data/url
            optional: true

      container:
        image: gcr.io/stackrox-infra/automation-flavors/demo:0.1.9
        imagePullPolicy: Always
        args:
          - create
          - "--name={{workflow.parameters.name}}"
          - "--main-image={{workflow.parameters.main-image}}"
          - --gcp-project=srox-temp-sales-demos
          - --dns-gcp-project=ultra-current-825
          - --creation-source=infra
          - --k8s-version={{workflow.parameters.k8s-version}}
        volumeMounts:
          - name: credentials
            mountPath: /tmp/google-credentials.json
            subPath: google-credentials.json
          - name: credentials
            mountPath: /tmp/google-scanner-credentials.json
            subPath: google-scanner-credentials.json
        env:
          - name: DOCKER_IO_USERNAME
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: DOCKER_IO_USERNAME
          - name: DOCKER_IO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: DOCKER_IO_PASSWORD
          - name: STACKROX_IO_USERNAME
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: STACKROX_IO_USERNAME
          - name: STACKROX_IO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: STACKROX_IO_PASSWORD
          - name: AUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: AUTH_CLIENT_ID
          - name: AUTH_DOMAIN
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: AUTH_DOMAIN
          - name: SLACK_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: SLACK_WEBHOOK
          - name: STACKROX_LICENSE
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: STACKROX_LICENSE

    - name: wait
      suspend: {}

    - name: destroy
      activeDeadlineSeconds: 3600
      inputs:
        artifacts:
          - name: tfstate
            path: /data/terraform.tfstate
            optional: true
          - name: tfvars
            path: /data/tfvars
            optional: true
      container:
        image: gcr.io/stackrox-infra/automation-flavors/demo:0.1.9
        imagePullPolicy: Always
        args:
          - destroy
        volumeMounts:
          - name: credentials
            mountPath: /tmp/google-credentials.json
            subPath: google-credentials.json
