apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aro-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: nodes
        value: "4"
      - name: machine-type
        value: "Standard_D4s_v3"

  templates:
    - name: start
      steps:
        - - name: create
            template: create

        - - name: wait
            template: wait

        - - name: destroy
            template: destroy

    - name: create
      outputs:
        artifacts:
          - name: kubeconfig
            path: /data/kubeconfig
            archive:
              none: {}
          - name: connect
            path: /data/connect.sh
            archive:
              none: {}
          - name: data
            path: /data
            archive:
              tar: {}
      container:
        image: gcr.io/stackrox-infra/automation-flavors/openshift-aro:0.2.12-4-g05e508ee80-snapshot
        imagePullPolicy: Always
        args:
          - create
          - "{{workflow.parameters.name}}"
          - srox-temp-dev-test
        env:
          - name: AZURE_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                name: aro-cluster-manager
                key: AZURE_SUBSCRIPTION_ID
          - name: AZURE_SP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: aro-cluster-manager
                key: AZURE_SP_CLIENT_ID
          - name: AZURE_SP_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: aro-cluster-manager
                key: AZURE_SP_TENANT_ID
          - name: NODE_COUNT
            value: "{{workflow.parameters.nodes}}"
          - name: INSTANCE_TYPE
            value: "{{workflow.parameters.machine-type}}"
          - name: CREATION_SOURCE
            value: "infra"
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          emptyDir: {}

    - name: wait
      suspend: {}

    - name: destroy
      container:
        image: gcr.io/stackrox-infra/automation-flavors/openshift-aro:0.2.12-4-g05e508ee80-snapshot
        imagePullPolicy: Always
        args:
          - destroy
          - "{{workflow.parameters.name}}"
          - srox-temp-dev-test
        env:
          - name: AZURE_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                name: aro-cluster-manager
                key: AZURE_SUBSCRIPTION_ID
          - name: AZURE_SP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: aro-cluster-manager
                key: AZURE_SP_CLIENT_ID
          - name: AZURE_SP_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: aro-cluster-manager
                key: AZURE_SP_TENANT_ID
