apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: openshift-multi-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: crio
      - name: nodes
      - name: machine-type
      - name: zone
        value: ""
      - name: install-monitoring
      - name: install-metrics
  volumes:
    - name: credentials
      secret:
        secretName: google-credentials-openshift

  templates:
    - name: start
      steps:
        - - name: create
            template: create
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.name}}"
                - name: crio
                  value: "{{workflow.parameters.crio}}"
                - name: nodes
                  value: "{{workflow.parameters.nodes}}"
                - name: machine-type
                  value: "{{workflow.parameters.machine-type}}"
                - name: zone
                  value: "{{workflow.parameters.zone}}"
                - name: install-monitoring
                  value: "{{workflow.parameters.install-monitoring}}"
                - name: install-metrics
                  value: "{{workflow.parameters.install-metrics}}"

        - - name: wait
            template: wait
        - - name: destroy
            template: destroy
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.name}}"
              artifacts:
                - name: terraform-destroy-plan
                  from: "{{steps.create.outputs.artifacts.terraform-destroy-plan}}"

    - name: create
      activeDeadlineSeconds: 3600
      inputs:
        parameters:
          - name: name
          - name: crio
          - name: zone
      outputs:
        artifacts:
          - name: kubeconfig
            path: /well-known/artifacts/config
            archive:
              none: {}
          - name: console_url
            path: /well-known/artifacts/console_url
            archive:
              none: {}
          - name: console_password
            path: /well-known/artifacts/console_passwd
            archive:
              none: {}
          - name: grafana_url
            path: /well-known/artifacts/grafana_url
            archive:
              none: {}
          - name: prometheus_url
            path: /well-known/artifacts/prometheus_url
            archive:
              none: {}
          - name: SSH_ACCESS
            path: /well-known/artifacts/SSH_ACCESS.md
            archive:
              none: {}
          - name: data
            path: /well-known
            archive:
              tar: {}
          # internal use
          - name: terraform-destroy-plan
            path: /well-known/artifacts/terraform-destroy.tfplan

      container:
        image: gcr.io/stackrox-infra/automation-flavors/openshift-multi:0.2.11
        args:
          - create
          - "--name={{inputs.parameters.name}}"
          - "--crio={{inputs.parameters.crio}}"
          - --creation-source=infra
          - "--zone={{inputs.parameters.zone}}"
        env:
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: google-credentials-openshift
                key: google-credentials.json

    - name: wait
      suspend: {}

    - name: destroy
      activeDeadlineSeconds: 3600
      inputs:
        parameters:
          - name: name
        artifacts:
          - name: terraform-destroy-plan
            path: /well-known/artifacts/terraform-destroy.tfplan
      container:
        image: gcr.io/stackrox-infra/automation-flavors/openshift-multi:0.2.11
        args:
          - destroy
        env:
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: google-credentials-openshift
                key: google-credentials.json
