apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: openshift-multi-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: crio
      - name: nodes
      - name: machine-type
      - name: zone
        value: ""
      - name: install-monitoring
      - name: install-metrics
  volumes:
    - name: credentials
      secret:
        secretName: google-credentials-openshift

  templates:
    - name: start
      steps:
        - - name: create
            template: create
            arguments:
              parameters:
                - name: name
                  value: '{{ "{{" }}workflow.parameters.name{{ "}}" }}'
                - name: crio
                  value: '{{ "{{" }}workflow.parameters.crio{{ "}}" }}'
                - name: nodes
                  value: '{{ "{{" }}workflow.parameters.nodes{{ "}}" }}'
                - name: machine-type
                  value: '{{ "{{" }}workflow.parameters.machine-type{{ "}}" }}'
                - name: zone
                  value: '{{ "{{" }}workflow.parameters.zone{{ "}}" }}'
                - name: install-monitoring
                  value: '{{ "{{" }}workflow.parameters.install-monitoring{{ "}}" }}'
                - name: install-metrics
                  value: '{{ "{{" }}workflow.parameters.install-metrics{{ "}}" }}'

        - - name: wait
            template: wait
        - - name: destroy
            template: destroy
            arguments:
              parameters:
                - name: name
                  value: '{{ "{{" }}workflow.parameters.name{{ "}}" }}'
              artifacts:
                - name: terraform-destroy-plan
                  from: '{{ "{{" }}steps.create.outputs.artifacts.terraform-destroy-plan{{ "}}" }}'

    - name: create
      activeDeadlineSeconds: 7200
      inputs:
        parameters:
          - name: name
          - name: crio
          - name: nodes
          - name: machine-type
          - name: zone
          - name: install-monitoring
          - name: install-metrics
      outputs:
        artifacts:
          - name: kubeconfig
            path: /well-known/artifacts/config
            archive:
              none: {}
          - name: console_url
            path: /well-known/artifacts/console_url
            archive:
              none: {}
          - name: console_password
            path: /well-known/artifacts/console_passwd
            archive:
              none: {}
          - name: grafana_url
            path: /well-known/artifacts/grafana_url
            archive:
              none: {}
          - name: prometheus_url
            path: /well-known/artifacts/prometheus_url
            archive:
              none: {}
          - name: SSH_ACCESS
            path: /well-known/artifacts/SSH_ACCESS.md
            archive:
              none: {}
          - name: data
            path: /well-known
            archive:
              tar: {}
          # internal use
          - name: terraform-destroy-plan
            path: /well-known/artifacts/terraform-destroy.tfplan

      container:
        # TODO(ROX-25537): Fix build for openshift-multi
        image: quay.io/stackrox-io/ci:automation-flavors-openshift-multi-0.10.12
        command:
          - /usr/bin/entrypoint
        args:
          - create
          - '--name={{ "{{" }}inputs.parameters.name{{ "}}" }}'
          - '--crio={{ "{{" }}inputs.parameters.crio{{ "}}" }}'
          - --creation-source=infra
          - '--zone={{ "{{" }}inputs.parameters.zone{{ "}}" }}'
          - '--nodes={{ "{{" }}inputs.parameters.nodes{{ "}}" }}'
          - '--machine-type={{ "{{" }}inputs.parameters.machine-type{{ "}}" }}'
          - '--install-metrics={{ "{{" }}inputs.parameters.install-metrics{{ "}}" }}'
          - '--install-monitoring={{ "{{" }}inputs.parameters.install-monitoring{{ "}}" }}'
          - --gcp-project=acs-team-temp-dev
          - --dns-project=acs-team-temp-dev
          - --dns-zone=ocp-infra-rox-systems
        env:
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: openshift-4-gcp-service-account
                key: google-credentials.json

    - name: wait
      suspend: {}

    - name: destroy
      activeDeadlineSeconds: 3600
      inputs:
        parameters:
          - name: name
        artifacts:
          - name: terraform-destroy-plan
            path: /well-known/artifacts/terraform-destroy.tfplan
      container:
        # TODO(ROX-25537): Fix build for openshift-multi
        image: quay.io/stackrox-io/ci:automation-flavors-openshift-multi-0.10.12
        command:
          - /usr/bin/entrypoint
        args:
          - destroy
        env:
          - name: GOOGLE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: openshift-4-gcp-service-account
                key: google-credentials.json
