apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: openshift-lite-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: zone
        value: ""
  volumes:
    - name: credentials
      secret:
        secretName: google-credentials-openshift

  templates:
    - name: start
      steps:
        - - name: create
            template: create
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.name}}"

        - - name: wait
            template: wait
        - - name: destroy
            template: destroy
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.name}}"
              artifacts:
                - name: terraform-destroy-plan
                  from: "{{steps.create.outputs.artifacts.terraform-destroy-plan}}"

    - name: create
      activeDeadlineSeconds: 3600
      inputs:
        parameters:
          - name: name
      outputs:
        artifacts:
          - name: kubeconfig
            path: /well-known/artifacts/config
          - name: terraform-destroy-plan
            path: /well-known/artifacts/terraform-destroy.tfplan
          - name: SSH_ACCESS.md
            path: /well-known/artifacts/SSH_ACCESS.md
            archive:
              none: {}
      container:
        image: gcr.io/stackrox-infra/automation-flavors/openshift-lite:0.2.4-6-g5eb20cf23f-snapshot
        args:
          - create
          - "--name={{inputs.parameters.name}}"
          - --creation-source=infra
          - "--zone={{inputs.parameters.zone}}"
        volumeMounts:
          - name: credentials
            mountPath: /tmp/google-credentials.json
            subPath: google-credentials.json

    - name: wait
      suspend: {}

    - name: destroy
      activeDeadlineSeconds: 3600
      inputs:
        parameters:
          - name: name
        artifacts:
          - name: terraform-destroy-plan
            path: /well-known/artifacts/terraform-destroy.tfplan
      container:
        image: gcr.io/stackrox-infra/automation-flavors/openshift-lite:0.2.4-6-g5eb20cf23f-snapshot
        args:
          - destroy
        volumeMounts:
          - name: credentials
            mountPath: /tmp/google-credentials.json
            subPath: google-credentials.json
