apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gke-default-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: nodes
      - name: machine-type
  volumes:
    - name: credentials
      secret:
        secretName: google-credentials

  templates:
    - name: start
      steps:
        - - name: create
            template: create
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.name}}"
                - name: nodes
                  value: "{{workflow.parameters.nodes}}"
                - name: machine-type
                  value: "{{workflow.parameters.machine-type}}"

        - - name: wait
            template: wait
        - - name: destroy
            template: destroy
            arguments:
              parameters:
                - name: name
                  value: "{{steps.create.outputs.parameters.cluster_name}}"

    - name: create
      inputs:
        parameters:
          - name: name
          - name: nodes
          - name: machine-type
      outputs:
        artifacts:
          - name: kubeconfig
            path: /outputs/kubeconfig
          - name: connect
            path: /outputs/connect.sh
        parameters:
          - name: cluster_name
            valueFrom:
              path: /outputs/cluster_name
      container:
        image: gcr.io/stackrox-infra/automation-flavors/gke-default:0.0.7
        args:
          - create
          - "--name={{inputs.parameters.name}}"
          - "--nodes={{inputs.parameters.nodes}}"
          - "--machine-type={{inputs.parameters.machine-type}}"
          - --gcp-project=srox-temp-dev-test
          - --creation-source=infra
        volumeMounts:
          - name: credentials
            mountPath: /tmp

    - name: wait
      suspend: {}

    - name: destroy
      inputs:
        parameters:
          - name: name
      container:
        image: gcr.io/stackrox-infra/automation-flavors/gke-default:0.0.7
        args:
          - destroy
          - "--name={{inputs.parameters.name}}"
          - --gcp-project=srox-temp-dev-test
        volumeMounts:
          - name: credentials
            mountPath: /tmp
