apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: qa-demo-

spec:
  entrypoint: start
  onExit: stop
  imagePullSecrets:
    - name: docker-io-pull-secret
    - name: stackrox-io-pull-secret
    - name: quay-rhacs-eng-pull-secret

  arguments:
    parameters:
      - name: name
      - name: main-image
      - name: central-db-image
        value: ""
      - name: scanner-image
        value: ""
      - name: scanner-db-image
        value: ""
      - name: k8s-version
        value: ""
      - name: enable-psps
        value: ""

  volumes:
    - name: credentials
      secret:
        secretName: google-credentials-demo

  templates:
    - name: start
      steps:
        - - name: roxctl
            template: roxctl

        - - name: create
            template: create
            arguments:
              artifacts:
                - name: roxctl
                  from: "{{steps.roxctl.outputs.artifacts.roxctl}}"

        - - name: wait
            template: wait

    - name: stop
      steps:
        - - name: destroy
            template: destroy
            arguments:
              artifacts:
                - name: tfstate
                  from: "{{workflow.outputs.artifacts.global-tfstate}}"
                - name: tfvars
                  from: "{{workflow.outputs.artifacts.global-tfvars}}"

    - name: roxctl
      activeDeadlineSeconds: 120
      outputs:
        artifacts:
          - name: roxctl
            path: /tmp/roxctl
      container:
        image: "{{workflow.parameters.main-image}}"
        imagePullPolicy: Always
        command:
          - cp
        args:
          - --dereference
          - -v
          - /stackrox/roxctl
          - /tmp/roxctl

    - name: create
      activeDeadlineSeconds: 3600
      inputs:
        artifacts:
          - name: roxctl
            path: /usr/bin/roxctl
          - name: dns-cert
            path: /certs/cert.pem
            gcs:
              bucket: sr-demo-files
              key: certs/demos.rox.systems/privkey-plus-fullchain.pem
              serviceAccountKeySecret:
                name: google-credentials-demo
                key: read-certs-google-credentials.json

      outputs:
        artifacts:
          - name: kubeconfig
            path: /data/kubeconfig.yaml
            optional: true

          - name: tfstate
            globalName: global-tfstate
            path: /data/terraform.tfstate
            optional: true

          - name: tfvars
            globalName: global-tfvars
            path: /data/tfvars
            optional: true

          - name: url
            path: /data/url
            optional: true

          - name: admin-password
            path: /data/admin_password
            optional: true
            archive:
              none: {}

          - name: SSH_ACCESS
            path: /data/SSH_ACCESS.md
            archive:
              none: {}

      container:
        image: quay.io/stackrox-io/ci:automation-flavors-demo-0.7.11-3-g0ce5aa7da8-snapshot
        imagePullPolicy: Always
        command:
          - /usr/bin/entrypoint
        args:
          - create
          - "--name={{workflow.parameters.name}}"
          - "--main-image={{workflow.parameters.main-image}}"
          - "--scanner-image={{workflow.parameters.scanner-image}}"
          - "--scanner-db-image={{workflow.parameters.scanner-db-image}}"
          - "--central-db-image={{workflow.parameters.central-db-image}}"
          - --gcp-project=acs-team-temp-dev
          - --dns-gcp-project=acs-team-temp-dev
          - --creation-source=infra
          - --k8s-version={{workflow.parameters.k8s-version}}
          - --enable-psps={{workflow.parameters.enable-psps}}
        volumeMounts:
          - name: credentials
            mountPath: /tmp/google-credentials.json
            subPath: google-credentials.json
          - name: credentials
            mountPath: /tmp/image-read-google-credentials.json
            subPath: image-read-google-credentials.json
        env:
          - name: QUAY_RHACS_ENG_RO_USERNAME
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: QUAY_RHACS_ENG_RO_USERNAME
          - name: QUAY_RHACS_ENG_RO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: QUAY_RHACS_ENG_RO_PASSWORD
          - name: STACKROX_IO_USERNAME
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: STACKROX_IO_USERNAME
          - name: STACKROX_IO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: STACKROX_IO_PASSWORD
          - name: SLACK_WEBHOOK
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: SLACK_WEBHOOK
          - name: GCP_CLOUD_DNS_ZONE_NAME
            value: "demos-rox-systems"
          - name: DOMAIN_NAME
            value: "demos.rox.systems"

    - name: wait
      suspend: {}

    - name: destroy
      activeDeadlineSeconds: 3600
      inputs:
        artifacts:
          - name: tfstate
            path: /data/terraform.tfstate
            optional: true
          - name: tfvars
            path: /data/tfvars
            optional: true
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-demo-0.7.11-3-g0ce5aa7da8-snapshot
        imagePullPolicy: Always
        command:
          - /usr/bin/entrypoint
        args:
          - destroy
        volumeMounts:
          - name: credentials
            mountPath: /tmp/google-credentials.json
            subPath: google-credentials.json
