apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: rosa-
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
      - name: rosa-args
        value: ""
      - name: aws-region
        value: "us-east-2"
      - name: managed-cp
        value: false
      - name: nodes
        value: "4"
      - name: machine-type
        value: "m5.xlarge"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Mi

  templates:
    - name: start
      steps:
        - - name: create
            template: create

        - - name: gather
            template: gather

        - - name: wait
            template: wait

        - - name: destroy
            template: destroy

    - name: create
      activeDeadlineSeconds: 7200
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-rosa-0.8.5-22-g105197fe80-snapshot
        imagePullPolicy: Always
        command:
          - ./entrypoint.sh
        args:
          - create
          - "{{workflow.parameters.name}}"
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: REDHAT_PULL_SECRET_BASE64
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: REDHAT_PULL_SECRET_BASE64
          - name: OPENSHIFT_CLUSTER_MANAGER_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: OPENSHIFT_CLUSTER_MANAGER_API_TOKEN
          - name: AWS_DEFAULT_REGION
            value: "{{workflow.parameters.aws-region}}"
          - name: AWS_REGION
            value: "{{workflow.parameters.aws-region}}"
          - name: MANAGED_CP
            value: "{{workflow.parameters.managed-cp}}"
          - name: NODE_COUNT
            value: "{{workflow.parameters.nodes}}"
          - name: INSTANCE_TYPE
            value: "{{workflow.parameters.machine-type}}"
          - name: CREATION_SOURCE
            value: "infra"
        volumeMounts:
          - name: data
            mountPath: /data

    - name: gather
      script:
        image: busybox
        command: [sh]
        source: |
          cd /data
          . ./dotenv
          echo "${CONSOLE_ENDPOINT}" > cluster-console-url
          echo "${CONSOLE_USER}" > cluster-console-username
          echo "${CONSOLE_PASSWORD}" > cluster-console-password
        volumeMounts:
          - name: data
            mountPath: /data
      outputs:
        artifacts:
          - name: kubeconfig
            path: /data/kubeconfig
            archive:
              none: {}
          - name: dotenv
            path: /data/dotenv
            archive:
              none: {}
          - name: data
            path: /data
            archive:
              tar: {}
          - name: cluster-console-url
            path: /data/cluster-console-url
            archive:
              none: {}
          - name: cluster-console-username
            path: /data/cluster-console-username
            archive:
              none: {}
          - name: cluster-console-password
            path: /data/cluster-console-password
            archive:
              none: {}

    - name: wait
      suspend: {}

    - name: destroy
      activeDeadlineSeconds: 3600
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-rosa-0.8.5-22-g105197fe80-snapshot
        imagePullPolicy: Always
        command:
          - ./entrypoint.sh
        args:
          - destroy
          - "{{workflow.parameters.name}}"
        env:
          - name: ROSA_ARGS
            value: "{{workflow.parameters.rosa-args}}"
          - name: AWS_DEFAULT_REGION
            value: "{{workflow.parameters.aws-region}}"
          - name: AWS_REGION
            value: "{{workflow.parameters.aws-region}}"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: OPENSHIFT_CLUSTER_MANAGER_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: OPENSHIFT_CLUSTER_MANAGER_API_TOKEN
          - name: REDHAT_PULL_SECRET_BASE64
            valueFrom:
              secretKeyRef:
                name: osd-access-secrets
                key: REDHAT_PULL_SECRET_BASE64
        volumeMounts:
          - name: data
            mountPath: /data
