apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gke-default-
  labels:
    needsExit: true
  annotations:
    infra.stackrox.com/lifespan: 0s
    infra.stackrox.com/lifespanlast: 1s
spec:
  entrypoint: start
  onExit: stop
  arguments:
    parameters:
      - name: name
      - name: nodes
      - name: machine-type
      - name: k8s-version
        value: ""
      - name: pod-security-policy
        value: ""
      - name: gcp-image-type
        value: ""
      - name: gcp-zone
        value: ""

  volumes:
    - name: credentials
      secret:
        secretName: google-credentials

  templates:
    - name: start
      steps:
        - - name: create
            template: echo
            arguments:
              parameters:
              - name: message
                value: "create"
          - name: wait
            template: wait
            arguments:
              parameters:
              - name: oldlifespan
                value: "3h0m0s"

    - name: stop
      steps:
        - - name: destroy
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.name}}"

    - name: wait
      inputs:
        parameters:
          - name: oldlifespan
      steps:
        - - name: echo1
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{inputs.parameters.oldlifespan}} =? {{workflow.annotations.infra.stackrox.com/lifespan}}"
        - - name: echoD
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{=sprig.dateModify(workflow.annotations.infra.stackrox.com/lifespan, workflow.creationTimestamp)}}"
        - - name: echoD2
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{=sprig.dateModify('30h',workflow.creationTimestamp)}}"
        - - name: echoD3
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{sprig.dateModify(workflow.annotations.infra.stackrox.com/lifespan, workflow.creationTimestamp)}}"
        - - name: delay
            template: delay
        - - name: echo2
            template: echo
            when: "'{{inputs.parameters.oldlifespan}}' =~ '{{workflow.annotations.infra.stackrox.com/lifespan}}'"
            arguments:
              parameters:
              - name: message
                value: "{{inputs.parameters.oldlifespan}} =~ {{workflow.annotations.infra.stackrox.com/lifespan}}"
        - - name: echo3
            template: echo
            when: "'{{inputs.parameters.oldlifespan}}' !~ '{{workflow.annotations.infra.stackrox.com/lifespan}}'"
            arguments:
              parameters:
              - name: message
                value: "{{inputs.parameters.oldlifespan}} !~ {{workflow.annotations.infra.stackrox.com/lifespan}}"
        - - name: echo4
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{inputs.parameters.oldlifespan}}, {{workflow.annotations.infra.stackrox.com/lifespan}}"
        - - name: shortloop
            template: wait
            when: "'{{inputs.parameters.oldlifespan}}' =~ '{{workflow.annotations.infra.stackrox.com/lifespan}}'"
            arguments:
              parameters:
                - name: oldlifespan
                  value: "{{workflow.annotations.infra.stackrox.com/lifespan}}"  # preserve value; prevent pass by reference
        - - name: timeupdate
            template: timeupdate
        - - name: echoE
            template: echo
            arguments:
              parameters:
              - name: message
                value: "{{inputs.parameters.oldlifespan}} =? {{workflow.annotations.infra.stackrox.com/lifespan}}"
        - - name: echoE2
            template: argosay
            arguments:
              parameters:
              - name: foo
                value: 5
              - name: message
                value: "{{workflow.annotations.infra.stackrox.com/lifespan}}"  # preserve value; prevent pass by reference
        - - name: loop
            template: wait
            arguments:
              parameters:
                - name: oldlifespan
                  value: "{{workflow.annotations.infra.stackrox.com/lifespan}}"  # preserve value; prevent pass by reference

    - name: argosay
      inputs:
        parameters:
          - name: foo
          - name: message
      container:
        image: argoproj/argosay:v2
        # in this example, we use `asInt` to cast a parameter (which are ALWAYS strings) to an int so we can
        # multiply by 10
        args:
          - echo
          - |
            hello {{=asInt(inputs.parameters.foo) * 10}} @ {{=sprig.date('2006', workflow.creationTimestamp)}}
            {{inputs.parameters.message}}

    - name: echo
      inputs:
        parameters:
        - name: message
      container:
        image: alpine:3.7
        command: [echo, "{{inputs.parameters.message}}"]

    - name: delay
      suspend:
        duration: "4"

    - name: timeupdate
      script:
        image: quay.io/stackrox-io/ci:automation-flavors-gke-default-0.7.6-3-g1ce65fe441-snapshot
        imagePullPolicy: Always
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /tmp/google-credentials.json
        command: [bash, -x]
        source: |
          lifespan={{workflow.annotations.infra.stackrox.com/lifespan}};
          gcloud auth activate-service-account --key-file /tmp/google-credentials.json;
          gcloud auth list;
          gcloud config set compute/zone "{{workflow.parameters.gcp-zone}}";
          gcloud config set core/disable_prompts True;
          gcloud container clusters update \
            "{{workflow.parameters.name}}"\
            --project=srox-temp-dev-test\
            "--update-labels=lifespan=${lifespan}";
          echo "$lifespan" | tee /outputs/value.txt
        volumeMounts:
          - name: credentials
            mountPath: /tmp
      outputs:
        parameters:
        - name: value
          valueFrom:
            path: /outputs/value.txt
               
    - name: create
      activeDeadlineSeconds: 3600
      outputs:
        artifacts:
          - name: kubeconfig
            path: /outputs/kubeconfig
            mode: 0644
            archive:
              none: {}
          - name: connect
            path: /outputs/connect.sh
            mode: 0755
            archive:
              none: {}
          - name: SSH_ACCESS
            path: /outputs/SSH_ACCESS.md
            archive:
              none: {}
        parameters:
          - name: cluster_name
            valueFrom:
              path: /outputs/cluster_name
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-gke-default-0.7.6-3-g1ce65fe441-snapshot
        imagePullPolicy: Always
        command:
          - /usr/bin/entrypoint
        args:
          - create
          - "--name={{workflow.parameters.name}}"
          - "--nodes={{workflow.parameters.nodes}}"
          - "--machine-type={{workflow.parameters.machine-type}}"
          - --gcp-project=srox-temp-dev-test
          - --creation-source=infra
          - --labels=lifespan={{workflow.annotations.infra.stackrox.com/lifespan}}
          - --k8s-version={{workflow.parameters.k8s-version}}
          - --pod-security-policy={{workflow.parameters.pod-security-policy}}
          - --gcp-image-type={{workflow.parameters.gcp-image-type}}
          - --gcp-zone={{workflow.parameters.gcp-zone}}
        volumeMounts:
          - name: credentials
            mountPath: /tmp

    - name: destroy
      activeDeadlineSeconds: 3600
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-gke-default-0.5.3
        imagePullPolicy: Always
        command:
          - /usr/bin/entrypoint
        args:
          - destroy
          - "--name={{workflow.parameters.name}}"
          - --gcp-project=srox-temp-dev-test
          - --gcp-zone={{workflow.parameters.gcp-zone}}
        volumeMounts:
          - name: credentials
            mountPath: /tmp
