version: "2"
output:
  formats:
    text:
      path: stdout
    junit-xml:
      path: report.xml
linters:
  default: none
  enable:
    - asciicheck
    - copyloopvar
    - forbidigo
    - gocritic
    - gosec
    - govet
    - ineffassign
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
  settings:
    gosec:
      includes:
        - G601
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
      settings:
        printf:
          funcs:
            - Print
            - Printf
            - Println
            - Debug
            - Debugf
            - Info
            - Infof
            - Warn
            - Warnf
            - Error
            - Errorf
    nolintlint:
      require-explanation: false
      require-specific: true
      allow-unused: false
    revive:
      confidence: 0
    staticcheck:
      checks:
        - -SA1019
        - -SA4001
        - -ST1000
        - -ST1001
        - -ST1003
        - -ST1005
        - -ST1016
        - all
    wrapcheck:
      ignore-sig-regexps:
        - utils\.Should
        - errox\..+\.CausedBy(f)?
        - retry\.MakeRetryable
        - policy\.NewErr.*
  exclusions:
    generated: lax
    rules:
      - linters:
          - forbidigo
          - wrapcheck
        path: _test\.go
      - linters:
          - revive
        text: should have a package comment
      - linters:
          - revive
        text: should not use dot imports
      - linters:
          - revive
        text: returns unexported type .* which can be annoying to use
      - linters:
          - revive
        text: error strings should not be capitalized or end with punctuation or a newline
      - linters:
          - revive
        text: should omit type int from declaration
      - linters:
          - revive
        text: don't use leading k in Go names
      - linters:
          - revive
        text: avoid meaningless package names
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
