[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.9.4"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.22.0"

[[constraint]]
  name = "gopkg.in/golang/protobuf.v1"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"
