argo-workflows:
  namespaceOverride: argo
  server:
    authModes:
      - server

  controller:
    # Default values that will apply to all Workflows from this controller, unless overridden on the Workflow-level
    workflowDefaults:
      metadata:
        annotations:
          argo: workflows
      spec:
        ttlStrategy:
          # Keep the workflow objects available for 7 days
          secondsAfterCompletion: 604800
          secondsAfterSuccess: 604800
          secondsAfterFailure: 604800

  artifactRepository:
    archiveLogs: true
    gcs:
      bucket: rhacs-infra-artifacts
      serviceAccountKeySecret:
        name: gcs-credentials
        key: credentials.json
