apiVersion: v1
appVersion: latest
description: A Helm chart for infra-server
name: infra-server
version: 0.2.10
home: https://github.com/stackrox/infra
sources:
  - https://github.com/stackrox/infra
annotations:
  acsDemoVersion: 4.10.2
  automationFlavorsVersion: 0.12.10
  ocpCredentialsMode: Passthrough
dependencies:
  - name: argo-workflows
    version: "1.0.4"
    repository: "https://argoproj.github.io/argo-helm"
  - name: kube-prometheus-stack
    version: "83.5.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
