name: Cache UI Dependencies
description: Cache UI Dependencies
inputs:
  lockFile: 
    description: Where the monorepo lock is written
    required: true
    default: "go/src/github.com/stackrox/infra/ui/monorepo.lock"
runs:
  using: composite
  steps:
    - name: Cache UI Dependencies
      uses: actions/cache@v3
      with:
        path: |
          /github/home/.cache/Cypress
          /usr/local/share/.cache
          go/src/github.com/stackrox/infra/ui/node_modules
        key: npm-v2-${{ hashFiles(inputs.lockFile) }}
        restore-keys: |
          npm-v2-
