---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: workflow-controller
  name: workflow-controller-metrics
  namespace: argo
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: workflow-controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: infra-server
  name: infra-server-metrics
  namespace: infra
spec:
  ports:
  - name: metrics
    port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app.kubernetes.io/name: infra-server
