
---

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: azure-secrets
  namespace: default

data:
  AZURE_SP_USERNAME: |-
    {{ .Values.azure.sp_username| b64enc }}
  AZURE_SP_PASSWORD: |-
    {{ .Values.azure.sp_password | b64enc }}
  AZURE_SP_TENANT: |-
    {{ .Values.azure.sp_tenant | b64enc }}
