---

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: google-credentials-qa-demo
  namespace: default

data:
  # Service account used for provisioning demo infrastructure.
  google-credentials.json: |-
    {{- include "require-file" (list "qa-demo/qa-demo-provisioner.json" .) | b64enc | nindent 4 }}

  # Service account used for demo GCR integration.
  google-scanner-credentials.json: |-
    {{- include "require-file" (list "demo/google-scanner-credentials.json" .) | b64enc | nindent 4 }}
