---

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: google-credentials-qa-demo
  namespace: default

data:
  # Service account used for provisioning demo infrastructure.
  google-credentials.json: |-
    {{ required ".Values.qa_demo__qa_demo_provisioner_json is undefined" .Values.qa_demo__qa_demo_provisioner_json }}

  # Service account used for demo GCR integration.
  google-scanner-credentials.json: |-
    {{ required ".Values.demo__google_scanner_credentials_json is undefined" .Values.demo__google_scanner_credentials_json }}
