version: 2.1

defaults: &defaults
  docker:
    - image: docker.io/stackrox/apollo-ci:0.1.11-31-g63504e3520
      auth:
        username: $DOCKER_IO_PULL_USERNAME
        password: $DOCKER_IO_PULL_PASSWORD
  working_directory: /go/src/github.com/stackrox/infra

jobs:
  build-infra:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Build infra server binary
        command: make server

  build-infractl:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build infractl client binary
          command: make cli

workflows:
  version: 2
  build:
    jobs:
    - build-infra:
        context: docker-io-pull
    - build-infractl:
        context: docker-io-pull
