---

apiVersion: networking.gke.io/v1
kind: ManagedCertificate

metadata:
  name: infra-server-certificate
  namespace: infra

spec:
  domains:
    - {{ .Values.hosts.primary }}
    - {{ .Values.hosts.secondary }}
