{{ if ne .Values.deployment "local" -}}
---

apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate

metadata:
  name: infra-server-certificate
  namespace: infra

spec:
  domains:
    - {{ .Values.hosts.primary }}
    - {{ .Values.hosts.secondary }}
{{ end }}
