apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Release.Name }}-configs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}

binaryData:
  infra.toml: |-
    {{ .Files.Get "configs/infra.toml" | b64enc }}
