{{- if .Capabilities.APIVersions.Has "networking.gke.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: infra-server-ingress
  namespace: infra
  labels:
    app.kubernetes.io/name: infra-server
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.reservedAddressName }}
    networking.gke.io/managed-certificates: "infra-server-certificate"
spec:
  defaultBackend:
    service:
      name: infra-server-service
      port:
        number: 8443
{{ end }}
