{{ if ne .Values.deployment "local" -}}
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: infra-server-ingress
  namespace: infra
  labels:
    app.kubernetes.io/name: infra-server
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.reservedAddressName }}
    networking.gke.io/managed-certificates: "infra-server-certificate"
spec:
  backend:
    serviceName: infra-server-service
    servicePort: 8443
{{ end }}
