apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}

spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: {{ .Values.ip }}
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80

    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}

