apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gke-lite
  generateName: gke-lite-
  annotations:
    infra.stackrox.io/name: gke-lite
    infra.stackrox.io/description: A lightweight single node GKE cluster
    infra.stackrox.io/availability: alpha
spec:
  entrypoint: start
  arguments:
    parameters:
# name is mandatory
      - name: name
        description: cluster name
# nodes & machine-type are optional with defaults
      - name: nodes
        description: number of nodes
        default: 1
      - name: machine-type
        description: node machine type
        default: e2-standard-2
# these other parameters are optional without defaults at the workflow level.
# presumably good defaults are provided by the automation-flavors image.
      - name: k8s-version
        description: GKE kubernetes version
        default: ""
      - name: pod-security-policy
        description: Enables the pod security policy admission controller for the cluster
        default: ""
      - name: gcp-image-type
        description: The GCP image type to use for the cluster
        default: ""
      - name: gcp-zone
        description: The zone in GCP to create the cluster in
        default: ""

  volumes:
    - name: credentials
      secret:
        secretName: google-credentials

  templates:
    - name: start
      steps:
        - name: create
          template: create
        - name: wait
          template: wait
        - name: destroy
          template: destroy
          arguments:
            parameters:
              - name: name
                value: "{{steps.create.outputs.parameters.cluster_name}}"

    - name: create
      activeDeadlineSeconds: 3600
      outputs:
        artifacts:
          - name: kubeconfig
            path: /outputs/kubeconfig
            mode: 0644
            archive:
              none: {}
          - name: connect
            path: /outputs/connect.sh
            mode: 0755
            archive:
              none: {}
          - name: SSH_ACCESS
            path: /outputs/SSH_ACCESS.md
            archive:
              none: {}
        parameters:
          - name: cluster_name
            valueFrom:
              path: /outputs/cluster_name
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-gke-default-0.3.11
        imagePullPolicy: Always
        command:
          - /usr/bin/entrypoint
        args:
          - create
          - "--name={{workflow.parameters.name}}"
          - "--nodes={{workflow.parameters.nodes}}"
          - "--machine-type={{workflow.parameters.machine-type}}"
          - --gcp-project=srox-temp-dev-test
          - --creation-source=infra
          - --k8s-version={{workflow.parameters.k8s-version}}
          - --pod-security-policy={{workflow.parameters.pod-security-policy}}
          - --gcp-image-type={{workflow.parameters.gcp-image-type}}
          - --gcp-zone={{workflow.parameters.gcp-zone}}
        volumeMounts:
          - name: credentials
            mountPath: /tmp

    - name: wait
      suspend: {}

    - name: destroy
      activeDeadlineSeconds: 3600
      container:
        image: quay.io/stackrox-io/ci:automation-flavors-gke-default-0.3.11
        imagePullPolicy: Always
        command:
          - /usr/bin/entrypoint
        args:
          - destroy
          - "--name={{workflow.parameters.name}}"
          - --gcp-project=srox-temp-dev-test
          - --gcp-zone={{workflow.parameters.gcp-zone}}
        volumeMounts:
          - name: credentials
            mountPath: /tmp
