apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: simulate
  generateName: simulate-
  annotations:
    infra.stackrox.io/description: Simulates the standard workflow of create, wait and destroy
    infra.stackrox.io/availability: alpha
spec:
  entrypoint: start
  arguments:
    parameters:
      - name: name
        description: cluster name
      - name: create-delay-seconds
        description: how long to spend in create
        default: 10
      - name: create-outcome
        description: success or fail
        default: success
      - name: destroy-delay-seconds
        description: how long to spend in destroy
        default: 10
      - name: destroy-outcome
        description: success or fail
        default: success

  templates:
    - name: start
      steps:
        - - name: create
            template: simulate
            arguments:
              parameters:
              - name: delay-seconds
                value: "{{ workflow.parameters.create-delay-seconds }}"
              - name: outcome
                value: "{{ workflow.parameters.create-outcome }}"
        - - name: wait
            template: wait
        - - name: destroy
            template: simulate
            arguments:
              parameters:
              - name: delay-seconds
                value: "{{ workflow.parameters.destroy-delay-seconds }}"
              - name: outcome
                value: "{{ workflow.parameters.destroy-outcome }}"

    - name: simulate
      inputs:
        parameters:
        - name: delay-seconds
        - name: outcome
      script:
        image: debian:9.4
        command: [bash]
        source: |
          set -x
          start=0
          while sleep 1; do
            if [[ $((start++)) -ge {{inputs.parameters.delay-seconds}} ]]; then
              break
            fi
          done
          [[ "{{inputs.parameters.outcome}}" == "success" ]] || exit 1

    - name: wait
      suspend: {}
