apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: google-credentials-openshift-4
  namespace: default

data:
  google-credentials.json: |-
    {{ required ".Values.openshift_4__google_credentials_json is undefined" .Values.openshift_4__google_credentials_json }}


---

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: redhat-pull-secret
  namespace: default

data:
  REDHAT_PULL_SECRET: |-
    {{ required ".Values.openshift_4__redhat_pull_secret_json is undefined" .Values.openshift_4__redhat_pull_secret_json }}
