apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: openshift-4-gcp-service-account
  namespace: default

data:
  google-credentials.json: |-
    {{ required ".Values.openshift_4__gcp_service_account_key_json is undefined" .Values.openshift_4__gcp_service_account_key_json }}


---

# (deprecated) this secret is used for openshift-4 provisioning with
# stackrox.com GCP and can be removed once the migration away from that account
# and its projects are complete. In the meantime this must remain to facilitate
# drain and rollback if required.
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: google-credentials-openshift-4
  namespace: default

data:
  google-credentials.json: |-
    {{ required ".Values.openshift_4__google_credentials_json is undefined" .Values.openshift_4__google_credentials_json }}


---

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: redhat-pull-secret
  namespace: default

data:
  REDHAT_PULL_SECRET: |-
    {{ required ".Values.openshift_4__redhat_pull_secret_json is undefined" .Values.openshift_4__redhat_pull_secret_json }}
