apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: google-credentials-openshift-4
  namespace: default

data:
  google-credentials.json: |-
    {{- include "require-file" (list "openshift-4/google-credentials.json" .) | b64enc | nindent 4 }}


---

apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: redhat-pull-secret
  namespace: default

data:
  REDHAT_PULL_SECRET: |-
    {{- include "require-file" (list "openshift-4/redhat-pull-secret.json" .) | b64enc | nindent 4 }}
