---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: aro-cluster-manager
  namespace: default
data:
  AZURE_SUBSCRIPTION_ID: |-
    {{ .Values.aroClusterManager.azureSubscriptionId | b64enc }}
  AZURE_SP_CLIENT_ID: |-
    {{ .Values.aroClusterManager.azureSPClientId | b64enc }}
  AZURE_SP_TENANT_ID: |-
    {{ .Values.aroClusterManager.azureSPTenantId | b64enc }}
  AZURE_SP_SECRET_VAL: |-
    {{ .Values.aroClusterManager.azureSPSecretVal | b64enc }}
  REDHAT_PULL_SECRET_BASE64: |-
    {{ .Values.aroClusterManager.redHatPullSecretBase64 | b64enc }}
