#!/bin/bash

main() {
    local filename="infractl-CHECKSUMS"
    pushd bin/ >/dev/null || exit 1
    rm -f "${filename}"
    shasum -a 512 -- infractl-* > "${filename}"
    popd >/dev/null || exit 1

}

main "$@"
