#!/bin/sh

main() {
    # Current time in epoch seconds.
    local BUILD_TIMESTAMP="$(date +'%s')"


    # The Git short SHA for the current commit.
    local STABLE_GIT_SHORT_SHA="$(git rev-parse --short HEAD)"

    # The Git describe string for the current commit.
    local STABLE_GIT_VERSION="$(make --quiet tag)"

    CGO_ENABLED=0 exec go build -ldflags="-s -w \
        -X github.com/stackrox/infra/pkg/buildinfo/internal.buildTimestampUnixSeconds=$BUILD_TIMESTAMP \
        -X github.com/stackrox/infra/pkg/buildinfo/internal.circleciWorkflowURL=$STABLE_CIRCLECI_WORKFLOW_URL \
        -X github.com/stackrox/infra/pkg/buildinfo/internal.gitShortSha=$STABLE_GIT_SHORT_SHA \
        -X github.com/stackrox/infra/pkg/buildinfo/internal.gitVersion=$STABLE_GIT_VERSION" \
        "$@"
}

main "$@"
