apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: google-credentials-openshift
  namespace: default

data:
  google-credentials.json: |-
    {{- include "require-file" (list "openshift/google-credentials.json" .) | b64enc | nindent 4 }}
