apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: google-credentials-openshift
  namespace: default

data:
  google-credentials.json: |-
    {{ required ".Values.openshift__google_credentials_json is undefined" .Values.openshift__google_credentials_json }}
