---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: osd-access-secrets
  namespace: default
data:
  AWS_ACCESS_KEY_ID: |-
    {{ .Values.osdClusterManager.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: |-
    {{ .Values.osdClusterManager.awsSecretAccessKey | b64enc }}
  REDHAT_PULL_SECRET_BASE64: |-
    {{ .Values.osdClusterManager.redHatPullSecretBase64 | b64enc }}
  OPENSHIFT_CLUSTER_MANAGER_API_TOKEN: |-
    {{ .Values.osdClusterManager.openshiftClusterManagerApiToken | b64enc }}
  GCP_SA_CREDS_JSON_BASE64: |-
    {{ .Values.osdClusterManager.gcpSaCredsJsonBase64 | b64enc }}
