apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dummy-integration-tests
  labels:
    build.appstudio.redhat.com/pipeline: "dummy-integration"
spec:
  params:
    - name: MESSAGE
      type: string
      description: |
        A message to send to the components at test.
      default: Hello world
    - name: SNAPSHOT
      type: string
    - name: NAMESPACE
      type: string
  results:
    - name: TEST_OUTPUT
      value: "$(tasks.verify.results.TEST_OUTPUT)"
  tasks:
    - name: verify
      params:
        - name: MESSAGE
          value: "$(params.MESSAGE)"
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: NAMESPACE
          value: $(params.NAMESPACE)
      taskSpec:
        results:
        - description: Short summary of the policy evaluation for each image
          name: TEST_OUTPUT
        steps:
          - name: verification
            image: ubuntu:latest
            env:
              - name: MESSAGE
                value: $(params.MESSAGE)
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
              - name: NAMESPACE
                value: $(params.NAMESPACE)
            script: |
              #!/usr/bin/env bash

              apt-get update && apt-get install -y jq

              echo "SNAPSHOT:"
              echo "${SNAPSHOT}" |jq

              echo "NAMESPACE"
              echo "${NAMESPACE}"

              TEST_OUTPUT="{\"output\": \"${MESSAGE}\"}"
              echo "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)
