name: Build & Push

on:
  workflow_call:

defaults:
  run:
    working-directory: go/src/github.com/stackrox/infra

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.51.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: go/src/github.com/stackrox/infra

      - name: Get NPM package access
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_ROX_GITHUB_TOKEN }}
        run: echo "//npm.pkg.github.com/:_authToken=\"$GITHUB_TOKEN\"" > ~/.npmrc

      - name: Setup env
        run: |
          GOPATH="$GITHUB_WORKSPACE/go"
          echo GOPATH="${GOPATH}" >> "$GITHUB_ENV"
          PATH="${PATH}:${GOPATH}/bin"
          echo PATH="${PATH}" >> "$GITHUB_ENV"

      - name: Generate src
        # This is committed at generated/ but building here ensure the make
        # targets do not go stale and that any updates are committed.
        run: |
          make proto-generated-srcs
          git diff --exit-code HEAD

      - name: Go Unit Test
        run: |
          make unit-test

      - name: Build Infra Server
        run: |
          make image

      - name: Build Certifier
        run: |
          cd certifier && make image
  
      - name: Login for image push
        uses: docker/login-action@v2
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.INFRA_IMAGE_PUSH }}

      - name: Push
        run: |
          make push
          cd certifer && make push
