name: Create cost report

on:
  push:
    branches:
      - tm/workflow-cluster-cost-estimation
  workflow_dispatch:

jobs:
  create-cost-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate to GCloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_BIGQUERY_INFRA_LOGGER_SA }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Install requirements
        run: |
          pip install -r ./scripts/cost-estimation/requirements.txt

      - name: Calculate costs
        run: |
          ./scripts/cost-estimation/calculate-costs.sh >> "${GITHUB_STEP_SUMMARY}"
