name: Deploy infra
run-name: >-
  ${{
    format('Deploy infra version {0} to {1}',
      inputs.version,
      inputs.environment
    )
  }}

env:
  PROJECT: acs-team-automation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Dev or Prod?
        required: true
        default: development
        type: choice
        options:
        - development
        - production
      version:
        description: Version, expanded to Github + Docker image tag
        required: true

jobs:
  wait-for-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [infra-server, infra-certifier]
    steps:
      - name: Wait for image
        uses: stackrox/actions/release/wait-for-image@v1
        with:
          token: ${{ secrets.QUAY_RHACS_ENG_BEARER_TOKEN }}
          image: rhacs-eng/${{ matrix.image }}:${{ inputs.version }}
          limit: 1800

  deploy:
    runs-on: ubuntu-latest
    needs: [wait-for-images]
    steps:
      - name: Show inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"

      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ inputs.version }}

      - name: Authenticate to GCloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.INFRA_DEPLOY_AUTOMATION_GCP_SA }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          install_components: "gke-gcloud-auth-plugin"

      - name: Deploy to ${{ inputs.environment }}
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
        run: |
          gcloud container clusters get-credentials infra-${{ inputs.environment }} \
            --project "${PROJECT}" \
            --region us-west2
          ENVIRONMENT=${{ inputs.environment }} make helm-deploy

      - name: Notify infra channel about new version
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "CVANK5K5W"
            text: "Infra (${{ inputs.environment }}) was updated."
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":ship::tada:*Infra (${{ inputs.environment }}) was updated to <${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ inputs.version }}|${{ inputs.version }}>."
