name: Deploy infra
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Dev or Prod?
        required: true
        default: development
        type: choice
        options:
        - local
        - development
        - production
      version:
        description: Version, expanded to Github + Docker image tag
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}

      - name: Authenticate to GCloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_INFRA_DEPLOY_AUTOMATION_SA }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Deploy to ${{ inputs.environment }}
        run: |
          gcloud auth list
          gsutil cat gs://infra-configuration/latest/configuration/${{ inputs.environment }}-values.yaml | wc -l
          # gcloud container clusters get-credentials infra-${{ inputs.environment }} \
          #   --project stackrox-infra \
          #   --region us-west2
          # make install-${{ inputs.environment }}-without-write
          gcloud container clusters get-credentials infra-development-clone-tom \
            --project stackrox-infra \
            --region us-west2
          make tag
          make install-${{ inputs.environment }}-without-write
