name: Lint, Build, Push

on:
  pull_request:
    types:
    - opened
    - synchronize
  create:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.46

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: go/src/github.com/stackrox/infra

      - name: Build
        run: |
          set -x
          pwd
          env | grep GO || true
          env | grep HOME || true
          ls
          ls "$GOPATH/src/github.com/stackrox/infra"
          GOPATH="$(pwd)/go"
          cd "$GOPATH/src/github.com/stackrox/infra"
          set +x
          make image

      - name: Login
        env:
          INFRA_IMAGE_PUSH: ${{ secrets.INFRA_IMAGE_PUSH }}
        run: docker login -u _json_key --password-stdin <<<"$INFRA_IMAGE_PUSH" https://us.gcr.io

      - name: Push
        run: |
          GOPATH="$HOME/go"
          cd "$GOPATH/src/github.com/stackrox/infra"
          make push | cat

      - name: Logout
        run: |
          docker logout https://us.gcr.io
