name: Lint, Build, Push

on:
  pull_request:
    types:
    - opened
    - synchronize
  create:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.46

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: go/src/github.com/stackrox/infra

      - name: Get NPM package access
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_ROX_GITHUB_TOKEN }}
        run: echo "//npm.pkg.github.com/:_authToken=\"$GITHUB_TOKEN\"" > ~/.npmrc

      - name: Build
        run: |
          GOPATH="$(pwd)/go"
          PATH="${PATH}:${GOPATH}/bin"
          cd "$GOPATH/src/github.com/stackrox/infra"
          make image

      - name: Login for image push
        env:
          INFRA_IMAGE_PUSH: ${{ secrets.INFRA_IMAGE_PUSH }}
        run: docker login -u _json_key --password-stdin <<<"$INFRA_IMAGE_PUSH" https://us.gcr.io

      - name: Push
        run: |
          GOPATH="$(pwd)/go"
          cd "$GOPATH/src/github.com/stackrox/infra"
          make push | cat

      - name: Logout
        run: |
          docker logout https://us.gcr.io
