name: Release Tagged

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

defaults:
  run:
    working-directory: go/src/github.com/stackrox/infra

jobs:

  lint:
    uses: ./.github/workflows/lint.yaml

  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    secrets: inherit
